### ISSUE TITLE
Saml2Handler.ServiceProviderConfiguration is null

### ISSUE THREAD

**Issue by theFra985** [jkmu/Saml2.Authentication.Core#4]
I've followed the instruction and the demo project but i always get a NullReferenceException because of the ServiceProviderConfiguration is null
Any suggestion?

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Saml2.Authentication.Core.Authentication.Saml2Handler.HandleSignIn()
   at Saml2.Authentication.Core.Authentication.Saml2Handler.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by jkmu** [comment]
You should provide settings for the service provider in your `appsettings.json` file.

**Comment by theFra985** [comment]
You mean the "Saml" section?
I've provided it
My `appsettings.json`
```JSON
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "Saml2": {
      "ServiceProviderConfiguration": {
        "EntityId": "https://example.com",
        "Name": "Saml2.auth",
        "AssertionConsumerServiceUrl": "/acs",
        "AssertionConsumerServiceUrl": "/User/Logout",
        "OmitAssertionSignatureCheck": true
      },
      "IdentityProviderConfiguration": [
        {
          "EntityId": "https://federation.example.com/adfs/ls/",
          "Name": "idp",
          "ForceAuth": "false",
          "IsPassive": "false",
          "SingleSignOnService": "https://federationexample.com/adfs/ls/",
          "SingleSignOutService": "https://federation.example.com/adfs/ls/Logout",
          "ArtifactResolveService": "https://federation.example.com/adfs/ls/ArtifactResolve",
          "Certificate": {
            "FileName": "provider.cer"
          }
       }
     ]
  }
}
```
And in my `Startup.cs`
```c#
services.AddScoped<IUserClaimsPrincipalFactory<ClaimsPrincipal>, UserClaimPrincipalFactory>();
services.Configure<Saml2Configuration>(Configuration.GetSection("Saml2"));
services.AddSaml();
services.AddAuthentication("saml2")
            .AddCookie(options => {
                    options.LoginPath = "/User/Login";
                    options.SlidingExpiration = true;
                    options.ExpireTimeSpan = TimeSpan.FromHours(1);
            })
            .AddSaml("saml2", options => {
                options.SignInScheme = "Cookies";
                options.IdentityProviderName = "idp";
            });
```

**Comment by jkmu** [comment]
I see your configuration is missing service provider certificate.  You also have two entries of `AssertionConsumerServiceUrl`. Also just for info. consider storing the certs in certificate store for production environments.

**Comment by doveblees** [comment]
the comment on setting up certs in the appropriate cert stores, at least on windows .. follow the original ported code setup for certs and customize accordingly .. you just need to properly make your pkcs12/pfx/cert with your SANS and intermediates .. once you have that .. powershell for certificate setup is there .. https://svn.softwareborsen.dk/oiosaml.net/trunk/setup/ .. pretty easy to customize. if you are linux/unix .. you might have some alternative steps for certificate setup .. https://github.com/PowerShell/PowerShell/issues/7213 .. best wishes.

**Comment by theFra985** [comment]
Thanks for the support
